# Generated by Django 3.2.6 on 2021-08-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='account',
            new_name='author',
        ),
    ]
